/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/untitled.glb')
  return (
    <group ref={group} {...props} dispose={null} >
      <group scale={1}>
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.001']} position={[-10.85, 3, -0.01]} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[10.3, -0.5, -2.64]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.001']} position={[-4.6, 2.1, 4.6]} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.001']} position={[-4.6, 5.1, 3.1]} />
      <mesh geometry={nodes.Plane057.geometry} material={nodes.Plane057.material} position={[-2.8, -0.07, 5.11]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.001']} position={[1.8, 0, 4.6]} />
      <mesh geometry={nodes.Plane008.geometry} material={nodes.Plane008.material} position={[37.51, 10.33, 6.95]} rotation={[Math.PI / 2, 0, 0]} scale={[0.75, 1, 0.75]} />
      <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} position={[37.55, 10.33, 6.95]} rotation={[Math.PI / 2, 0, 0]} scale={[0.79, 1, 0.75]} />
      <mesh geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} position={[38.23, 10.33, 6.99]} rotation={[Math.PI / 2, 0, 0]} scale={[0.78, 1, 0.75]} />
      <mesh geometry={nodes.Plane011.geometry} material={nodes.Plane011.material} position={[38.23, 10.33, 6.99]} rotation={[Math.PI / 2, 0, 0]} scale={[0.78, 1, 0.75]} />
      <mesh geometry={nodes.Plane012.geometry} material={nodes.Plane012.material} position={[37.55, 10.33, 6.95]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane029.geometry} material={nodes.Plane029.material} position={[28.3, 1.54, 5.69]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane025.geometry} material={materials.Material} position={[-1.99, 1.35, 4.1]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane026.geometry} material={nodes.Plane026.material} position={[-1.96, 4.35, 2.6]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane027.geometry} material={nodes.Plane027.material} position={[2.51, 4.35, 0.59]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane028.geometry} material={materials.Material} position={[2.55, 1.35, 0.62]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane030.geometry} material={nodes.Plane030.material} position={[-1.72, 1.35, -8.36]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane031.geometry} material={nodes.Plane031.material} position={[-3.86, 4.35, -6.2]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane032.geometry} material={nodes.Plane032.material} position={[-3.86, 4.35, -2.3]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane033.geometry} material={nodes.Plane033.material} position={[-3.86, 4.35, 0.6]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane034.geometry} material={nodes.Plane034.material} position={[-3.86, 1.35, -2.98]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane035.geometry} material={nodes.Plane035.material} position={[-3.86, 1.35, 1.63]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane037.geometry} material={nodes.Plane037.material} position={[0.59, 1.12, 4.1]} rotation={[Math.PI / 2, 0, 0]} scale={[1.13, 1, 1.06]} />
      <mesh geometry={nodes.Plane036.geometry} material={nodes.Plane036.material} position={[0.59, 4.12, 2.6]} rotation={[Math.PI / 2, 0, 0]} scale={[1.13, 1, 1.06]} />
      <mesh geometry={nodes.Plane038.geometry} material={nodes.Plane038.material} position={[4.57, 4.35, -3.33]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.51, 1, 0.75]} />
      <mesh geometry={nodes.Plane039.geometry} material={nodes.Plane039.material} position={[4.57, 4.35, -5.93]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.51, 1, 0.75]} />
      <mesh geometry={nodes.Plane040.geometry} material={nodes.Plane040.material} position={[4.55, 1.35, -5.94]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.51, 1, 0.75]} />
      <mesh geometry={nodes.Plane041.geometry} material={nodes.Plane041.material} position={[4.55, 1.35, -3.32]} rotation={[1.57, 0, -Math.PI / 2]} scale={[0.51, 1, 0.75]} />
      <mesh geometry={nodes.Plane042.geometry} material={nodes.Plane042.material} position={[4.63, 4.46, -7.81]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.65, 1, 0.91]} />
      <mesh geometry={nodes.Plane043.geometry} material={nodes.Plane043.material} position={[4.61, 1.46, -7.78]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.65, 1, 0.91]} />
      <mesh geometry={nodes.Plane044.geometry} material={nodes.Plane044.material} position={[1.39, 4.36, -8.27]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.65, 1, 0.79]} />
      <mesh geometry={nodes.Plane045.geometry} material={nodes.Plane045.material} position={[0.11, 4.35, -8.23]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.51, 1, 0.75]} />
      <mesh geometry={nodes.Plane046.geometry} material={nodes.Plane046.material} position={[0.1, 1.35, -8.24]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.51, 1, 0.75]} />
      <mesh geometry={nodes.Plane047.geometry} material={nodes.Plane047.material} position={[-3.09, 4.35, -8.23]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.51, 1, 0.75]} />
      <mesh geometry={nodes.Plane048.geometry} material={nodes.Plane048.material} position={[-3.78, 1.34, -7.17]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.65, 1, 0.79]} />
      <mesh geometry={nodes.Plane049.geometry} material={nodes.Plane049.material} position={[-3.78, 1.34, -5.72]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.65, 1, 0.79]} />
      <mesh geometry={nodes.Plane050.geometry} material={materials['Material.001']} position={[-7.57, 1.32, -3.38]} />
      <mesh geometry={nodes.Plane051.geometry} material={materials['Material.001']} position={[-5.73, 2.86, 5.49]} />
      <mesh geometry={nodes.Plane063.geometry} material={nodes.Plane063.material} position={[-2.88, 3.37, 5.4]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.48]} />
      <mesh geometry={nodes.Plane052.geometry} material={materials['Material.001']} position={[2.47, 2.86, 5.49]} />
      <mesh geometry={nodes.Plane053.geometry} material={nodes.Plane053.material} position={[0.65, 0, 5.55]} scale={-0.15} />
      <mesh geometry={nodes.Plane054.geometry} material={materials['Material.002']} position={[-7.3, 3.32, 2.81]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[-3.52, 2.9, 5.7]} scale={[0.08, 0.1, 0.1]} />
      <mesh geometry={nodes.Plane055.geometry} material={materials['Material.002']} position={[-8.99, 4.83, 5.53]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[3.22, 6.3, 0.67]} scale={[0.08, 0.3, 0.08]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[2.94, 6.3, 0.67]} scale={[0.08, 0.3, 0.08]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[2.65, 6.3, 0.67]} scale={[0.08, 0.3, 0.08]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[2.37, 6.3, 0.67]} scale={[0.08, 0.3, 0.08]} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[2.09, 6.3, 0.67]} scale={[0.08, 0.3, 0.08]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.002']} position={[-3.44, 5.3, 4.17]} scale={0.15} />
      <mesh geometry={nodes.Plane056.geometry} material={nodes.Plane056.material} position={[-2.74, -0.01, 6.14]} />
      <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[-7.55, 1, 8.9]} scale={[0.15, 1, 0.15]} />
      <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[-6.68, 0, -9.28]} />
      <mesh geometry={nodes.Plane058.geometry} material={nodes.Plane058.material} position={[7.48, 0, -9.28]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Plane059.geometry} material={nodes.Plane059.material} position={[-2.87, 3, 3.12]} />
      <mesh geometry={nodes.Plane060.geometry} material={nodes.Plane060.material} position={[4.43, 5.99, -8.09]} />
      <mesh geometry={nodes.Plane061.geometry} material={nodes.Plane061.material} position={[-2.92, 6, 1.17]} />
      <mesh geometry={nodes.Plane062.geometry} material={materials.Material} position={[-2.88, 3.4, 5.4]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.48]} />
      <mesh geometry={nodes.Plane064.geometry} material={nodes.Plane064.material} position={[-6.3, -0.08, -8.91]} />
      <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[4.86, 5.03, -2.62]} scale={[0.22, 0.22, 0.14]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.002']} position={[4.66, 5.03, -2.3]} scale={[0.17, 0.22, 0.04]} />
      <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[-3.97, 5.02, -7.17]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.17, 0.23, 0.02]} />
      <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[-3.97, 5.02, -7.17]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.17, 0.23, 0.02]} />
      <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[-3.97, 5.02, -7.17]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.17, 0.23, 0.02]} />
      <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[-3.97, 5.02, -7.17]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.17, 0.23, 0.02]} />
      <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[-3.97, 5.02, -7.17]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.17, 0.23, 0.02]} />
      <mesh geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[-3.97, 5.02, -7.17]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.17, 0.23, 0.02]} />
      <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[-3.97, 5.02, -7.17]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.17, 0.23, 0.02]} />
      <mesh geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[-4.33, 4.77, -2.25]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.17, 0.23, 0.02]} />
      <mesh geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[-4.33, 4.77, 0.65]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.17, 0.23, 0.02]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.003']} position={[4.02, 1, -0.14]} scale={[0.78, 1.04, 0.78]} />
      <mesh geometry={nodes.Plane065.geometry} material={materials['Material.004']} position={[2.55, 1.35, 0.62]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane066.geometry} material={materials['Material.004']} position={[2.55, 1.35, 0.62]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane067.geometry} material={materials['Material.004']} position={[2.55, 1.35, 0.62]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane068.geometry} material={materials.Material} position={[2.55, 1.35, 0.62]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane069.geometry} material={materials['Material.004']} position={[-1.99, 1.35, 4.1]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane070.geometry} material={materials['Material.004']} position={[-1.99, 1.35, 4.1]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane071.geometry} material={materials['Material.004']} position={[-1.99, 1.35, 4.1]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Plane072.geometry} material={materials.Material} position={[-1.99, 1.35, 4.1]} rotation={[Math.PI / 2, 0, 0]} scale={[0.81, 1, 0.75]} />
      <mesh geometry={nodes.Balcony_.geometry} material={nodes.Balcony_.material} position={[913.68, 0, 309.67]} scale={3.89} />
      <mesh geometry={nodes.Bathroom.geometry} material={nodes.Bathroom.material} position={[286.09, 0, -763.07]} scale={3.89} />
      <mesh geometry={nodes.Bathroom001.geometry} material={nodes.Bathroom001.material} position={[1383.62, 0, -766.3]} scale={3.89} />
      <mesh geometry={nodes.Bathroom002.geometry} material={nodes.Bathroom002.material} position={[1205.3, 0, -763.36]} scale={3.89} />
      <mesh geometry={nodes.Bedroom_.geometry} material={nodes.Bedroom_.material} position={[256.51, 0, -481.49]} scale={3.89} />
      <mesh geometry={nodes.Bedroom_001.geometry} material={nodes.Bedroom_001.material} position={[1322.34, 0, -478.6]} scale={3.89} />
      <mesh geometry={nodes.Bedroom_002.geometry} material={nodes.Bedroom_002.material} position={[911.27, 0, -562.66]} scale={3.89} />
      <mesh geometry={nodes.Car_Porc.geometry} material={nodes.Car_Porc.material} position={[233.08, 0, 266.75]} scale={3.89} />
      <mesh geometry={nodes.Dining_4.geometry} material={nodes.Dining_4.material} position={[-220.64, 0, -331.81]} scale={3.89} />
      <mesh geometry={nodes.Dress_13.geometry} material={nodes.Dress_13.material} position={[103, 0, -739]} scale={3.89} />
      <mesh geometry={nodes.First_Fl.geometry} material={nodes.First_Fl.material} position={[1347.2, 0, 732.96]} scale={12.49} />
      <mesh geometry={nodes.Ground_F.geometry} material={nodes.Ground_F.material} position={[1346.56, 0, 665.22]} scale={12.49} />
      <mesh geometry={nodes.Kitchen_.geometry} material={nodes.Kitchen_.material} position={[-217.75, 0, -671.9]} scale={3.89} />
      <mesh geometry={nodes.Living_4.geometry} material={nodes.Living_4.material} position={[-183.1, 0, 36.31]} scale={3.89} />
      <mesh geometry={nodes.Sitout_4.geometry} material={nodes.Sitout_4.material} position={[-200.4, 0, 470.87]} scale={3.89} />
      <mesh geometry={nodes.Total_Fl.geometry} material={nodes.Total_Fl.material} position={[1341.58, 0, 802.39]} scale={12.49} />
      <mesh geometry={nodes.Upper_Li.geometry} material={nodes.Upper_Li.material} position={[908.56, 0, -146.36]} scale={3.89} />
    </group>
    </group>
  )
}

useGLTF.preload('/untitled.glb')
